version: '2'

services:
  db:
    build: mysql
    env_file: enviroments.private
    volumes:
      - /data/mysql:/var/lib/mysql

  bot:
    build: .
    depends_on:
      - db
    env_file: enviroments.private
    environment:
      MYSQL_HOST: db
    restart: always
